# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Contents.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contents(object):
    def setupUi(self, Contents):
        Contents.setObjectName("Contents")
        Contents.setWindowModality(QtCore.Qt.NonModal)
        Contents.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        Contents.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Contents.setWindowIcon(icon)
        Contents.setLayoutDirection(QtCore.Qt.LeftToRight)
        Contents.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(Contents)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(Contents)
        self.listView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setProperty("showDropIndicator", False)
        self.listView.setAlternatingRowColors(False)
        self.listView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listView.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 1, 0, 1, 1)

        self.retranslateUi(Contents)
        QtCore.QMetaObject.connectSlotsByName(Contents)

    def retranslateUi(self, Contents):
        _translate = QtCore.QCoreApplication.translate
        Contents.setWindowTitle(_translate("Contents", "目录"))
import res_rc
