# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextContent.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextContent(object):
    def setupUi(self, TextContent):
        TextContent.setObjectName("TextContent")
        TextContent.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        TextContent.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TextContent.setWindowIcon(icon)
        TextContent.setWindowOpacity(1.0)
        self.gridLayout = QtWidgets.QGridLayout(TextContent)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Next = QtWidgets.QPushButton(TextContent)
        self.pushButton_Next.setEnabled(True)
        self.pushButton_Next.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.gridLayout.addWidget(self.pushButton_Next, 2, 2, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(TextContent)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setSearchPaths([])
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 1, 1, 2)
        self.pushButton_Previous = QtWidgets.QPushButton(TextContent)
        self.pushButton_Previous.setEnabled(True)
        self.pushButton_Previous.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_Previous.setObjectName("pushButton_Previous")
        self.gridLayout.addWidget(self.pushButton_Previous, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(TextContent)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)

        self.retranslateUi(TextContent)
        QtCore.QMetaObject.connectSlotsByName(TextContent)
        TextContent.setTabOrder(self.pushButton_Previous, self.pushButton_Next)

    def retranslateUi(self, TextContent):
        _translate = QtCore.QCoreApplication.translate
        TextContent.setWindowTitle(_translate("TextContent", "斗破苍穹"))
        self.pushButton_Next.setText(_translate("TextContent", "下一条"))
        self.textBrowser.setHtml(_translate("TextContent", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\':/font/SourceHanSansSC-Regular_0.otf\'; font-size:16pt;\">默认文本</span></p></body></html>"))
        self.pushButton_Previous.setText(_translate("TextContent", "上一条"))
        self.label.setText(_translate("TextContent", "默认文本"))
import res_rc
